/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.University;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author harshikag
 */
public class StudentDashboardFinal extends javax.swing.JFrame {
    
    String[] semesterList = new String[]{"Fall 2021", "Spring 2021", "Summer 2021"};
    University uni = new University();
    StudentProfile student;
    ImageIcon studentLogo = new ImageIcon("studentLogo2.jpeg");
    ImageIcon homeIcon = new ImageIcon("HomeIcon.png");
    ImageIcon courseIcon = new ImageIcon("courseIcon.jpeg");
    ImageIcon registerIcon = new ImageIcon("registerIcon.png");
    ImageIcon feedbackIcon = new ImageIcon("feedbackIcon.png");
    ImageIcon transcriptIcon = new ImageIcon("transcriptIcon.jpeg");
    ImageIcon gradesIcon = new ImageIcon("gradesIcon.png");
    ImageIcon logoutIcon = new ImageIcon("logoutIcon.png");
    
    
    public void generateData() {
        // TODO add your handling code here:
        Department department1 = new Department("Information Systems");
        Department department2 = new Department("Engineering Management");

//        uni = 
        this.uni.getDepartmentList().add(department1);
        this.uni.getDepartmentList().add(department2);
        
       Course course = department1.newCourse("app eng", "info 5100", 4);        
       Course course1 = department2.newCourse("app dev", "info 5200", 4);
//
//
       CourseSchedule courseschedule = department1.newCourseSchedule("Fall 2021");       
//       CourseSchedule courseschedule = department2.newCourseSchedule("Fall 2021");      
      

//
       CourseOffer courseoffer = courseschedule.newCourseOffer("info 5100");        
       CourseOffer courseoffer1 = department2.newCourseSchedule("Fall 2021").newCourseOffer("info 5200");

       
       courseoffer.generatSeats(10);
       courseoffer1.generatSeats(20);        
       PersonDirectory pd = department1.getPersonDirectory();
       Person person = pd.newPerson("0112303");
       StudentDirectory sd = department1.getStudentDirectory();
       this.student = sd.newStudentProfile(person);
       CourseLoad courseload = student.newCourseLoad("Fall 2021"); 
       
//       PersonDirectory pd1 = department2.getPersonDirectory();
//       Person person1 = pd1.newPerson("0112304");
//       StudentDirectory sd1 = department2.getStudentDirectory();
//       this.student1 = sd1.newStudentProfile(person1);
//       CourseLoad courseload = student1.newCourseLoad("Fall 2021"); 

       courseload.newSeatAssignment(courseoffer);                
       courseload.newSeatAssignment(courseoffer1);
    }
    
    /**
     * Creates new form StudentDashboardFinal
     */
    public StudentDashboardFinal() {
        initComponents();
        logoLabel.setIcon(studentLogo);
        homeLabel.setIcon(homeIcon);
        courseLabelImg.setIcon(courseIcon);
        registerLabelImg.setIcon(registerIcon);
        feedbaclLabelImg.setIcon(feedbackIcon);
        transcriptLabelImg.setIcon(transcriptIcon);
        gradesLabelImg.setIcon(gradesIcon);
        logoutImgLabel.setIcon(logoutIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        HomeButton = new javax.swing.JButton();
        RegisterACourse = new javax.swing.JButton();
        Courses1 = new javax.swing.JButton();
        StudentFeedback = new javax.swing.JButton();
        TranscriptButton = new javax.swing.JButton();
        GradesButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        homeLabel = new javax.swing.JLabel();
        courseLabelImg = new javax.swing.JLabel();
        registerLabelImg = new javax.swing.JLabel();
        feedbaclLabelImg = new javax.swing.JLabel();
        transcriptLabelImg = new javax.swing.JLabel();
        gradesLabelImg = new javax.swing.JLabel();
        logoutImgLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(239, 242, 239));

        jPanel1.setBackground(new java.awt.Color(68, 71, 68));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 436));

        jLabel1.setBackground(new java.awt.Color(248, 248, 243));
        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 243));
        jLabel1.setText("Student");
        jLabel1.setSize(new java.awt.Dimension(70, 30));

        HomeButton.setBackground(new java.awt.Color(0, 0, 0));
        HomeButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(248, 248, 243));
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        RegisterACourse.setBackground(new java.awt.Color(0, 0, 0));
        RegisterACourse.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RegisterACourse.setForeground(new java.awt.Color(248, 248, 243));
        RegisterACourse.setText("Register");
        RegisterACourse.setBorderPainted(false);
        RegisterACourse.setContentAreaFilled(false);
        RegisterACourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterACourseActionPerformed(evt);
            }
        });

        Courses1.setBackground(new java.awt.Color(0, 0, 0));
        Courses1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Courses1.setForeground(new java.awt.Color(248, 248, 243));
        Courses1.setText("Courses");
        Courses1.setBorderPainted(false);
        Courses1.setContentAreaFilled(false);
        Courses1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Courses1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Courses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Courses1ActionPerformed(evt);
            }
        });

        StudentFeedback.setBackground(new java.awt.Color(0, 0, 0));
        StudentFeedback.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        StudentFeedback.setForeground(new java.awt.Color(248, 248, 243));
        StudentFeedback.setText("Feedback");
        StudentFeedback.setBorderPainted(false);
        StudentFeedback.setContentAreaFilled(false);
        StudentFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentFeedbackActionPerformed(evt);
            }
        });

        TranscriptButton.setBackground(new java.awt.Color(0, 0, 0));
        TranscriptButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TranscriptButton.setForeground(new java.awt.Color(248, 248, 243));
        TranscriptButton.setText("Transcript");
        TranscriptButton.setBorderPainted(false);
        TranscriptButton.setContentAreaFilled(false);
        TranscriptButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TranscriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranscriptButtonActionPerformed(evt);
            }
        });

        GradesButton.setBackground(new java.awt.Color(0, 0, 0));
        GradesButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        GradesButton.setForeground(new java.awt.Color(248, 248, 243));
        GradesButton.setText("Grades");
        GradesButton.setBorderPainted(false);
        GradesButton.setContentAreaFilled(false);
        GradesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(0, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(248, 248, 243));
        LogoutButton.setText("Logout");
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(transcriptLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradesLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logoutImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(feedbaclLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StudentFeedback))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(courseLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Courses1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 15, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TranscriptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(RegisterACourse))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Courses1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterACourse, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbaclLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TranscriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transcriptLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradesLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(239, 242, 239));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void GradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradesButtonActionPerformed

    private void TranscriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranscriptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TranscriptButtonActionPerformed

    private void StudentFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentFeedbackActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Department department1 = new Department("Information Systems");
        Department department2 = new Department("Engineering Management");

        University uni = new University();
        uni.getDepartmentList().add(department1);
        uni.getDepartmentList().add(department2);

        Course course = department1.newCourse("app eng", "info 5100", 4);
        Course course1 = department1.newCourse("app dev", "info 5200", 4);

        CourseSchedule courseschedule = department1.newCourseSchedule("Fall2020");

        CourseOffer courseoffer = courseschedule.newCourseOffer("info 5100");
        CourseOffer courseoffer1 = courseschedule.newCourseOffer("info 5200");

        courseoffer.generatSeats(10);
        courseoffer1.generatSeats(20);
        PersonDirectory pd = department1.getPersonDirectory();
        Person person = pd.newPerson("0112303");
        StudentDirectory sd = department1.getStudentDirectory();
        StudentProfile student = sd.newStudentProfile(person);
        CourseLoad courseload = student.newCourseLoad("Fall2020");

        courseload.newSeatAssignment(courseoffer);
        courseload.newSeatAssignment(courseoffer1); //register student in class
// //register student in class
        StudentEmployment se = new StudentEmployment(student, uni);
        jSplitPane1.setRightComponent(se);
    }//GEN-LAST:event_StudentFeedbackActionPerformed

    private void Courses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Courses1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Courses1ActionPerformed

    private void RegisterACourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterACourseActionPerformed
        // TODO add your handling code here:
        generateData();
        System.out.println(this.uni.getDepartmentList() + "  ....");
        CourseRegistration cr = new CourseRegistration(semesterList, this.uni);
        jSplitPane1.setRightComponent(cr);
    }//GEN-LAST:event_RegisterACourseActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDashboardFinal sd = new StudentDashboardFinal();
//                sd.setSize(1250, 680);
                sd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                sd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Courses1;
    private javax.swing.JButton GradesButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton RegisterACourse;
    private javax.swing.JButton StudentFeedback;
    private javax.swing.JButton TranscriptButton;
    private javax.swing.JLabel courseLabelImg;
    private javax.swing.JLabel feedbaclLabelImg;
    private javax.swing.JLabel gradesLabelImg;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoutImgLabel;
    private javax.swing.JLabel registerLabelImg;
    private javax.swing.JLabel transcriptLabelImg;
    // End of variables declaration//GEN-END:variables
}
